# Generated by Django 4.0.1 on 2022-01-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentBitcoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ultimo', models.DecimalField(decimal_places=2, max_digits=9)),
                ('abertura', models.DecimalField(decimal_places=2, max_digits=9)),
                ('alta', models.DecimalField(decimal_places=2, max_digits=9)),
                ('baixa', models.DecimalField(decimal_places=2, max_digits=9)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.RenameField(
            model_name='bitcoin',
            old_name='price',
            new_name='preco',
        ),
    ]
