# Generated by Django 4.0.1 on 2022-01-17 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0002_developmentbitcoin_rename_price_bitcoin_preco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developmentbitcoin',
            name='abertura',
        ),
        migrations.RemoveField(
            model_name='developmentbitcoin',
            name='alta',
        ),
        migrations.RemoveField(
            model_name='developmentbitcoin',
            name='baixa',
        ),
    ]
